name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git remote remove hf || true
          git remote add hf https://haseebahmed2003:$HF_TOKEN@huggingface.co/spaces/haseebahmed2003/ai-notes-generator

          git push hf main:main --force